[project]
name = "gitmatrix"
version = "0.3.0"
description = "Un client Git visuel et léger"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "PySide6>=6.5.0",
    "GitPython>=3.1.30",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
]

[project.scripts]
gitmatrix = "gitmatrix.app:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
gitmatrix = ["*.qss"]
